# Generated by Django 4.2.11 on 2024-07-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='price',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
