# Generated by Django 4.2.11 on 2024-07-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stadium_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
